;************************************************************
;Nombre: Oscar Garcia de Lara Parreño y Alba de Castro Martin
;Pareja: 6
;*************************************************************

; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
	CLR_PANT 		DB 	1BH,"[2","J$"
	PREG_CAD_HEX 	DB 	1BH,"[15;1fIntroduce una cadena en hexadecimal para convertir a decimal ? $"
	HEX_DEC			DB 	80 DUP (0)
	PREG_CAD_DEC 	DB 	1BH,"[15;1fIntroduce una cadena en decimal para convertir a hexadecimal ? $"
	DEC_HEX			DB 	80 DUP (0)	
	CAD_AUX DB 20 DUP (0)
	RESUL DB 20 DUP (0)
DATOS ENDS

; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0)
PILA ENDS

; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE,DS:DATOS,SS:PILA

; COMIENZO DEL PROCEDIMIENTO PRINCIPAL (START)
INICIO PROC FAR
;INICIALIZACION DE LOS REGISTROS DE SEGMENTO
	MOV AX,DATOS
	MOV DS,AX	;FIN DE LAS INICIALIZACIONES
	
	MOV AH,9	; BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	
	MOV DX,OFFSET PREG_CAD_HEX		;ESCRIBE "Introduce una cadena en hexadecimal...
	INT 21H
	
	MOV AH,0AH						;ALMACENA LA CADENA EN HEXADECIMAL TECLEADA
	MOV DX,OFFSET HEX_DEC
	MOV HEX_DEC[0], 7				;SE ALMACENA TEMPORALMENTE EN TEMP
	INT 21H
	
	MOV AH,9						;BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	MOV DX,OFFSET HEX_DEC
	INC DX
	INC DX
	MOV AH, 13H						;IMPRIME EN PANTALLA LA CONVERSION DE UN STRING HEXADECIMAL EN DECIMAL
	INT 60h
	
;===================================================
;DECIMAL A HEXADECIMAL	
;====================================================	
	mov ah, 0 
	int 16h ;LO MUESTRO POR PANTALLA
	
	MOV AH,9	; BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	
	
	MOV DX,OFFSET PREG_CAD_DEC		;ESCRIBE "Introduce una cadena en decimal...
	INT 21H
    
	MOV AH,0AH						;ALMACENA LA CADENA EN DECIMAL TECLEADA
	MOV DX,OFFSET DEC_HEX	
	MOV DEC_HEX[0], 7				;SE ALMACENA TEMPORALMENTE EN TEMP
	INT 21H
	
	
	MOV AH,9						;BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	MOV DX,OFFSET DEC_HEX
	INC DX
	INC DX
	MOV AX, 1200H					;IMPRIME EN PANTALLA LA CONVERSION DE UN STRING DECIMAL EN HEXADECIMAL
	INT 60h 
	
	mov ah, 0 
	int 16h 						;LO MUESTRO POR PANTALLA
	
	MOV AX,4C00H					;FIN DE PROGRAMA Y VUELTA AL DOS
	INT 21H
INICIO ENDP
;FIN DEL SEGMENTO DE CODIGO
CODE ENDS
;FIN DE PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO