;************************************************************
;Nombre: Oscar Garcia de Lara Parreño y Alba de Castro Martin
;Pareja: 6
;*************************************************************

; DEFINICION DEL SEGMENTO DE DATOS
DATOS SEGMENT
	CLR_PANT 			DB 	1BH,"[2","J$"
	CADENA_GUARDADA		DB 	80 DUP (0)
	PREG_CAD	 		DB 	1BH,"[15;1fIntroduce una cadena para convertir a hexadecimal ? $"
DATOS ENDS

; DEFINICION DEL SEGMENTO DE PILA
PILA SEGMENT STACK "STACK"
	DB 40H DUP (0)
PILA ENDS

; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE,DS:DATOS,SS:PILA

; COMIENZO DEL PROCEDIMIENTO PRINCIPAL (START)
INICIO PROC FAR
;INICIALIZACION DE LOS REGISTROS DE SEGMENTO
	MOV AX,DATOS
	MOV DS,AX						;FIN DE LAS INICIALIZACIONES
	
	MOV AH,9						;BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	
	MOV DX,OFFSET PREG_CAD			;ESCRIBE "Introduce una cadena...
	INT 21H
	
	MOV AH,0AH						;ALMACENA LA CADENA EN HEXADECIMAL TECLEADA
	MOV DX,OFFSET CADENA_GUARDADA
	MOV CADENA_GUARDADA[0], 7		;SE ALMACENA TEMPORALMENTE EN TEMP
	INT 21H
	
	MOV AH,9						;BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	MOV DX,OFFSET CADENA_GUARDADA
	INC DX
	INC DX
	MOV AH, 12H						;IMPRIME EN PANTALLA LA CONVERSION DE UN STRING HEXADECIMAL EN DECIMAL
	INT 60h
	
;======== LEER EL TECLADO =========	
	
principio:	;NO SE SALE DEL BUCLE SINO ESCRIBE QUIT
	XOR AX, AX						;AX=0
	INT 16h
	push ax
	MOV AH,9						;BORRA LA PANTALLA
	MOV DX, OFFSET CLR_PANT
	INT 21H
	pop ax
	CMP ah, 20h
	JE convertir					;SI AH=20h(d) SALTA A CONVERTIR 
	CMP ah, 10h						
	JE salir						;SI AH=10h(q) SALTA A SALIR
	JMP principio
convertir:	
	
	XOR AX, AX						;AX=0
	INT 16h
	CMP AH, 12h
	JNE principio					;SI AH<>12h(e) SALTA A PRINCIPIO
	
	XOR AX, AX						;AX=0
	INT 16h
	CMP AH, 2Eh
	JNE principio					;SI AH<>2Eh(c) SALTA A PRINCIPIO
	
	MOV DX,OFFSET CADENA_GUARDADA ;ULTIMA CADENA GUARDADA
	INC DX
	INC DX
	MOV AH, 14h    ;La 14h sirve para imprimir una cadena decimal de origen sin conversion, es un añadido para reutilizar
	INT 60h
	JMP principio
salir:	
	XOR AX, AX						;AX=0
	INT 16h
	CMP AH, 16h
	JNE principio					;SI AH<>16h(u) SALTA A PRINCIPIO
	
	XOR AX, AX						;AX=0
	INT 16h
	CMP AH, 17h
	JNE principio					;SI AH<>17h(i) SALTA A PRINCIPIO
	
	XOR AX, AX						;AX=0
	INT 16h
	CMP AH, 14h						
	JNE principio					;SI AH<>14h(t) SALTA A PRINCIPIO
	
	MOV AX,4C00H					;FIN DE PROGRAMA Y VUELTA AL DOS
	INT 21H
INICIO ENDP

;FIN DEL SEGMENTO DE CODIGO
CODE ENDS
;FIN DE PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO